[theme]
primaryColor = "#EE1C5B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
font = "serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
